permalink:           "/:title"

title:               PaltusStas
url:                 https://www.paltusstas.github.io
canonical_url:       'http://www.paltusstas.github.io'
description:         "Блог об IT-шных и не очень вещах"
paginate:            7
baseurl:             ""
logo:                '/public/logo.png'

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate #Деление главной на страницы
  - jekyll-gist #Интеграция GitHub Gists
  - jekyll-sitemap #Автоматическое построение карты сайта
  - jekyll-seo-tag #SEO-оптимизация


pages_list:    
  Sitemap: '/sitemap'   
  About: '/about'

tag_page: '/sitemap'
excerpt_separator: "<!--more-->"

# About
author:
  email:             paltusstas@gmail.com
  github:            https://github.com/PaltusStas
  vk:                https://vk.com/danielsafonov
  tg:                https://t.me/paltusstas

# Social
social:
  name: PaltusStas
  links:
    https://vk.com/danielsafonov
    https://t.me/paltusstas
    https://github.com/PaltusStas

# Google and Yandex verifications
webmaster_verifications:
  google: 
  yandex: 

# Language
lang: ru_RU